# Generated by Django 5.0.1 on 2024-01-29 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_footergalleryimage1_page_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='bg_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Задний фон в шапке'),
        ),
    ]
