# Generated by Django 5.0.1 on 2024-02-12 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_header_bg_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='body',
        ),
    ]
