# Generated by Django 5.0.1 on 2024-02-12 18:45

import wagtail.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_homepage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('textblock', wagtail.blocks.RichTextBlock(required=False)), ('card_block_list', wagtail.blocks.StreamBlock([('card', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('title', wagtail.blocks.CharBlock(max_length=255)), ('text', wagtail.blocks.RichTextBlock())]))])), ('second_block_list', wagtail.blocks.StreamBlock([('section_left', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('title', wagtail.blocks.RichTextBlock(max_length=255)), ('text', wagtail.blocks.RichTextBlock())])), ('section_right', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('title', wagtail.blocks.RichTextBlock(max_length=255)), ('text', wagtail.blocks.RichTextBlock())]))])), ('about_me', wagtail.blocks.StructBlock([('text', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())])), ('gallery', wagtail.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock())), ('videos', wagtail.blocks.ListBlock(wagtail.embeds.blocks.EmbedBlock()))], blank=True, use_json_field=True),
        ),
    ]
